import type { SkillProduct } from "@/lib/types";

const sharedAquascape = {
  videoSrc: "/demo/aquascape.mp4",
  accent: "#9cf26d",
  accentSoft: "#19351e",
  requirements: ["ChatGPT Work hoặc Codex có hỗ trợ Skill", "Ảnh bể hoặc mô tả ý tưởng", "Công cụ tạo video AI tương thích"],
};

const sharedAutomotive = {
  videoSrc: "/demo/automotive.mp4",
  accent: "#ff8a65",
  accentSoft: "#41231d",
  requirements: ["Trình tạo video AI tương thích", "Ảnh tham chiếu mẫu xe", "Khung hình 16:9 hoặc 9:16"],
};

const sharedProduct = {
  videoSrc: "/demo/product.mp4",
  accent: "#8bb8ff",
  accentSoft: "#182a44",
  requirements: ["Ảnh sản phẩm rõ nét", "Trình tạo video AI tương thích", "Mô tả thương hiệu cơ bản"],
};

export const skills: SkillProduct[] = [
  {
    ...sharedAquascape,
    slug: "nature-aquascape-v22",
    name: "Nature Aquascape",
    eyebrow: "Bố cục tự nhiên, đúng logic thủy sinh",
    shortDescription: "Tạo chuỗi video setup bể Nature với cây, rêu và mực nước hợp lý.",
    description: "Skill điều phối toàn bộ quá trình dựng bể Nature từ hardscape, nền, cây thủy sinh đến thả cá. Mỗi cảnh khóa trạng thái vật thể để video liền mạch và tránh chi tiết xuất hiện sai thời điểm.",
    price: 249000,
    category: "Aquascape",
    version: "V2.2",
    featured: true,
    deliverables: ["01 file Skill hoàn chỉnh", "Bộ quy tắc logic mực nước", "Mẫu prompt Nature tham khảo", "Hướng dẫn cài đặt nhanh"],
    outcomes: ["Cây và rêu nằm đúng vùng ngập nước", "Hardscape giữ nguyên giữa các cảnh", "Video có tiến trình setup rõ ràng"],
  },
  {
    ...sharedAquascape,
    slug: "iwagumi-stone-flow",
    name: "Iwagumi Stone Flow",
    eyebrow: "Tỷ lệ đá và khoảng trống cân bằng",
    shortDescription: "Khóa vị trí đá chính, đá phụ và thảm cây xuyên suốt từng shot.",
    description: "Skill chuyên cho bố cục Iwagumi tối giản, tập trung tỷ lệ đá, hướng dòng chảy và không gian âm để tạo video setup có chiều sâu.",
    price: 219000,
    category: "Aquascape",
    version: "V1.8",
    deliverables: ["01 file Skill", "Preset bố cục Iwagumi", "Checklist continuity", "Hướng dẫn sử dụng"],
    outcomes: ["Đá không đổi vị trí giữa cảnh", "Thảm cây phủ đúng tiến trình", "Bố cục giữ được độ tối giản"],
  },
  {
    ...sharedAquascape,
    slug: "dutch-garden-sequence",
    name: "Dutch Garden Sequence",
    eyebrow: "Phân tầng cây theo màu và chiều cao",
    shortDescription: "Dựng bể Hà Lan giàu màu sắc mà vẫn giữ đúng vị trí từng cụm cây.",
    description: "Skill chia cụm cây theo lớp, màu và tốc độ phát triển, phù hợp video biến đổi từ bể trống đến bể Hà Lan hoàn chỉnh.",
    price: 229000,
    category: "Aquascape",
    version: "V1.6",
    deliverables: ["01 file Skill", "Sơ đồ phân tầng cây", "Prompt mẫu 4 cảnh", "Hướng dẫn tùy biến"],
    outcomes: ["Cụm cây không đổi màu bất thường", "Tiền cảnh và hậu cảnh rõ lớp", "Mực nước nhất quán"],
  },
  {
    ...sharedAutomotive,
    slug: "supra-a90-final-assembly",
    name: "Supra A90 Final Assembly",
    eyebrow: "Lắp ráp đúng thứ tự, không nhảy chi tiết",
    shortDescription: "Tạo video mở hộp và lắp Toyota GR Supra A90 theo từng bộ phận.",
    description: "Skill kiểm soát thứ tự mở hộp, xếp chi tiết lên bàn và lắp ráp mô hình. Chi tiết chưa lắp không được xuất hiện trên xe ở bất kỳ cảnh nào.",
    price: 299000,
    category: "Automotive",
    version: "V2.5",
    featured: true,
    deliverables: ["01 file Skill V2.5", "06 prompt tách riêng", "Bộ khóa trạng thái linh kiện", "Hướng dẫn thay mẫu xe"],
    outcomes: ["Mỗi chi tiết chỉ xuất hiện đúng lúc", "Tỷ lệ mô hình nhất quán", "Không biến thành xe thật"],
  },
  {
    ...sharedAutomotive,
    slug: "porsche-911-model-build",
    name: "Porsche 911 Model Build",
    eyebrow: "Cinematic workshop assembly",
    shortDescription: "Quy trình lắp mô hình 911 với nhịp dựng điện ảnh và tỷ lệ ổn định.",
    description: "Skill tạo video lắp ráp mô hình Porsche trong studio thu nhỏ, có kiểm soát bàn làm việc, dụng cụ và trạng thái thân xe.",
    price: 279000,
    category: "Automotive",
    version: "V1.9",
    deliverables: ["01 file Skill", "05 prompt theo công đoạn", "Preset ánh sáng workshop", "Hướng dẫn đổi màu xe"],
    outcomes: ["Thân xe giữ đúng tỷ lệ", "Công cụ không tự xuất hiện", "Ánh sáng liên tục"],
  },
  {
    ...sharedAutomotive,
    slug: "engine-reveal-sequence",
    name: "Engine Reveal Sequence",
    eyebrow: "Tập trung cơ khí và chuyển động",
    shortDescription: "Reveal động cơ theo lớp với vật liệu kim loại rõ nét và logic lắp ráp.",
    description: "Skill dành cho video trình diễn động cơ, bóc tách cấu tạo và lắp từng lớp linh kiện trong không gian studio tối.",
    price: 259000,
    category: "Automotive",
    version: "V1.4",
    deliverables: ["01 file Skill", "04 prompt reveal", "Preset vật liệu kim loại", "Checklist lỗi thường gặp"],
    outcomes: ["Chi tiết máy không xuyên nhau", "Chuyển động có thứ tự", "Bề mặt kim loại rõ nét"],
  },
  {
    ...sharedProduct,
    slug: "luxury-product-reveal",
    name: "Luxury Product Reveal",
    eyebrow: "Hero video cho sản phẩm cao cấp",
    shortDescription: "Biến ảnh sản phẩm thành video reveal ánh sáng studio sang trọng.",
    description: "Skill tạo chuyển động máy quay, ánh sáng viền và nhịp reveal dành cho mỹ phẩm, phụ kiện và đồ công nghệ cao cấp.",
    price: 199000,
    category: "Product Video",
    version: "V1.7",
    featured: true,
    deliverables: ["01 file Skill", "05 phong cách ánh sáng", "Prompt mẫu theo ngành", "Hướng dẫn thay sản phẩm"],
    outcomes: ["Logo và hình dáng ít biến dạng", "Ánh sáng có chủ đích", "Kết thúc bằng hero frame"],
  },
  {
    ...sharedProduct,
    slug: "clean-unboxing-flow",
    name: "Clean Unboxing Flow",
    eyebrow: "Mở hộp gọn, sản phẩm luôn nhất quán",
    shortDescription: "Dựng video unboxing tối giản với từng phụ kiện được sắp xếp rõ ràng.",
    description: "Skill chia video unboxing thành các cảnh mở hộp, lấy từng món, sắp lên bàn và close-up sản phẩm mà không làm thay đổi bao bì.",
    price: 189000,
    category: "Product Video",
    version: "V1.5",
    deliverables: ["01 file Skill", "04 prompt unboxing", "Bộ khóa trạng thái hộp", "Hướng dẫn quay dọc"],
    outcomes: ["Không đổi màu hộp", "Phụ kiện đã lấy được giữ nguyên", "Khung hình sạch và dễ theo dõi"],
  },
  {
    ...sharedProduct,
    slug: "miniature-workshop-story",
    name: "Miniature Workshop Story",
    eyebrow: "Thế giới tí hon quanh sản phẩm",
    shortDescription: "Tạo đội thợ tí hon tương tác với sản phẩm theo một câu chuyện ngắn.",
    description: "Skill dựng video quảng cáo phong cách miniature, kiểm soát tỷ lệ nhân vật, đạo cụ và sản phẩm trong từng cảnh.",
    price: 219000,
    category: "Product Video",
    version: "V1.3",
    deliverables: ["01 file Skill", "06 mẫu tình huống", "Quy tắc tỷ lệ miniature", "Hướng dẫn tùy biến"],
    outcomes: ["Nhân vật giữ đúng tỷ lệ", "Sản phẩm là tâm điểm", "Câu chuyện có mở và kết"],
  },
  {
    ...sharedAquascape,
    slug: "forest-diorama-aquascape",
    name: "Forest Diorama Aquascape",
    eyebrow: "Chiều sâu rừng ngập nước",
    shortDescription: "Tạo bố cục rừng thủy sinh có phối cảnh sâu và đường dẫn tự nhiên.",
    description: "Skill kiểm soát tỷ lệ thân lũa, rêu và cây nền để dựng cảnh rừng ngập nước có chiều sâu mà không phá vỡ logic sinh học.",
    price: 239000,
    category: "Aquascape",
    version: "V1.7",
    deliverables: ["01 file Skill", "Preset phối cảnh rừng", "04 prompt dựng cảnh", "Checklist sinh học"],
    outcomes: ["Rêu nằm trong vùng ẩm/ngập phù hợp", "Tỷ lệ lũa tạo chiều sâu", "Cây không mọc xuyên kính"],
  },
  {
    ...sharedAutomotive,
    slug: "jdm-garage-transformation",
    name: "JDM Garage Transformation",
    eyebrow: "Từ xưởng trống đến chiếc xe hoàn thiện",
    shortDescription: "Chuỗi biến đổi garage JDM có trạng thái xe và bối cảnh nhất quán.",
    description: "Skill kể câu chuyện phục dựng xe trong garage, khóa trạng thái thân vỏ, bánh xe và môi trường ở mỗi mốc thời gian.",
    price: 269000,
    category: "Automotive",
    version: "V1.2",
    deliverables: ["01 file Skill", "05 prompt theo tiến trình", "Bảng trạng thái xe", "Hướng dẫn đổi garage"],
    outcomes: ["Xe tiến triển theo đúng thứ tự", "Garage không đổi cấu trúc", "Màu sơn nhất quán"],
  },
  {
    ...sharedProduct,
    slug: "food-commercial-motion",
    name: "Food Commercial Motion",
    eyebrow: "Chuyển động nguyên liệu giàu cảm giác",
    shortDescription: "Video quảng cáo đồ ăn với chuyển động nguyên liệu và hero shot cuối.",
    description: "Skill tạo video thực phẩm ngắn, kiểm soát chuyển động nguyên liệu, texture và khoảnh khắc đóng gói sản phẩm.",
    price: 209000,
    category: "Product Video",
    version: "V1.1",
    deliverables: ["01 file Skill", "05 cấu trúc chuyển động", "Prompt mẫu đồ ăn/đồ uống", "Hướng dẫn khung dọc"],
    outcomes: ["Nguyên liệu dễ nhận diện", "Chuyển động không quá hỗn loạn", "Hero shot rõ nhãn"],
  },
];

export const pageSize = 6;

export function getSkill(slug: string) {
  return skills.find((skill) => skill.slug === slug);
}

export function getSkillsPage(page: number) {
  const safePage = Math.min(Math.max(page, 1), Math.ceil(skills.length / pageSize));
  const start = (safePage - 1) * pageSize;
  return {
    items: skills.slice(start, start + pageSize),
    page: safePage,
    pages: Math.ceil(skills.length / pageSize),
    total: skills.length,
  };
}
