import type { SkillProduct } from "@/lib/types";

const aquascape = {
  videoSrc: "/demo/aquascape.mp4",
  accent: "#9cf26d",
  accentSoft: "#19351e",
  priceVnd: 249000,
  discountPercent: 0,
  internationalCheckoutUrl: null,
  requirements: [
    "ChatGPT Work or Codex with Skill support",
    "A tank photo or a clear layout brief",
    "A compatible AI image or video generator",
  ],
};

const automotive = {
  videoSrc: "/demo/automotive.mp4",
  accent: "#ff8a65",
  accentSoft: "#41231d",
  priceVnd: 299000,
  discountPercent: 0,
  internationalCheckoutUrl: null,
  requirements: [
    "A compatible AI video generator",
    "A clear vehicle reference image",
    "A 16:9 or 9:16 output format",
  ],
};

const product = {
  videoSrc: "/demo/product.mp4",
  accent: "#8bb8ff",
  accentSoft: "#182a44",
  priceVnd: 199000,
  discountPercent: 0,
  internationalCheckoutUrl: null,
  requirements: [
    "A clean product reference image",
    "A compatible AI video generator",
    "A short brand or visual direction brief",
  ],
};

export const skills: SkillProduct[] = [
  {
    ...aquascape,
    slug: "nature-aquascape-v22",
    name: "Nature Aquascape Director",
    eyebrow: "Biologically believable scenes with locked continuity",
    shortDescription: "Build a complete Nature-style aquarium sequence with consistent plants, water level and hardscape.",
    description: "A production-ready Skill for directing the full setup sequence—from substrate and hardscape to planting and fish release. Every scene locks object state, scale and water logic to reduce visual errors between generations.",
    priceUsdCents: 100,
    isFree: false,
    internationalCheckoutUrl: null,
    category: "Aquascape",
    version: "V2.2",
    featured: true,
    deliverables: ["Complete Skill file", "Water-level logic rules", "Nature layout prompt examples", "Quick installation guide"],
    outcomes: ["Plants and moss stay in believable wet zones", "Hardscape remains consistent between shots", "The setup follows a clear visual progression"],
  },
  {
    ...aquascape,
    slug: "iwagumi-stone-flow",
    name: "Iwagumi Prompt Starter",
    eyebrow: "A simple continuity starter for stone layouts",
    shortDescription: "Try a lightweight Iwagumi workflow before moving to an advanced aquascape Skill.",
    description: "A free starter Skill that helps you define the main stone, supporting stones and negative space across a short aquarium setup sequence.",
    priceUsdCents: 0,
    isFree: true,
    category: "Aquascape",
    version: "V1.0",
    deliverables: ["Starter Skill file", "Basic Iwagumi layout checklist", "One example workflow"],
    outcomes: ["Main stones keep their position", "Plant coverage follows a simple progression", "The composition stays visually minimal"],
  },
  {
    ...aquascape,
    slug: "dutch-garden-sequence",
    name: "Dutch Garden Sequence",
    eyebrow: "Plant groups controlled by color, height and depth",
    shortDescription: "Direct a colorful Dutch aquarium while preserving every plant group across shots.",
    description: "A structured Skill for dividing plants into foreground, midground and background groups while maintaining color and placement throughout the sequence.",
    priceUsdCents: 2700,
    isFree: false,
    category: "Aquascape",
    version: "V1.6",
    deliverables: ["Complete Skill file", "Plant-layer planning sheet", "Four-scene prompt structure", "Customization guide"],
    outcomes: ["Plant groups keep consistent colors", "Depth layers remain easy to read", "Water level stays consistent"],
  },
  {
    ...automotive,
    slug: "supra-a90-final-assembly",
    name: "Supra A90 Model Assembly",
    eyebrow: "Correct build order with no premature parts",
    shortDescription: "Create an unboxing and model-car assembly sequence where every component appears at the right stage.",
    description: "This Skill controls the unboxing, parts layout and assembly state of a 1:18 model car. Components that have not been installed are explicitly prevented from appearing on the vehicle.",
    priceUsdCents: 3500,
    isFree: false,
    category: "Model Assembly",
    version: "V2.5",
    featured: true,
    deliverables: ["Complete V2.5 Skill file", "Six separate prompt blocks", "Assembly-state locking rules", "Vehicle replacement guide"],
    outcomes: ["Parts appear only when installed", "Model scale stays consistent", "The miniature never turns into a full-size car"],
  },
  {
    ...automotive,
    slug: "porsche-911-model-build",
    name: "Porsche 911 Model Build",
    eyebrow: "Cinematic workshop assembly",
    shortDescription: "Build a miniature Porsche in a controlled studio with stable scale, tools and body state.",
    description: "A cinematic model-assembly Skill designed for clean workshop lighting, deliberate hand movement and reliable continuity across each construction stage.",
    priceUsdCents: 3300,
    isFree: false,
    category: "Model Assembly",
    version: "V1.9",
    deliverables: ["Complete Skill file", "Five stage-based prompts", "Workshop lighting preset", "Color replacement guide"],
    outcomes: ["The body keeps the correct scale", "Tools do not appear unexpectedly", "Lighting remains continuous"],
  },
  {
    ...automotive,
    slug: "engine-reveal-sequence",
    name: "Engine Reveal Sequence",
    eyebrow: "Mechanical layers, materials and movement",
    shortDescription: "Reveal an engine layer by layer with clear metal surfaces and believable assembly logic.",
    description: "A specialist Skill for cinematic engine reveals, exploded views and staged component assembly in a controlled dark studio.",
    priceUsdCents: 3000,
    isFree: false,
    category: "Automotive",
    version: "V1.4",
    deliverables: ["Complete Skill file", "Four reveal prompts", "Metal material preset", "Common-error checklist"],
    outcomes: ["Mechanical parts do not intersect", "Movement follows a logical order", "Metal surfaces stay crisp"],
  },
  {
    ...product,
    slug: "luxury-product-reveal",
    name: "Luxury Product Reveal",
    eyebrow: "Premium studio motion for hero products",
    shortDescription: "Turn a product image into a polished reveal with controlled rim light and camera movement.",
    description: "A commercial Skill for beauty, accessories and technology products. It directs camera motion, light sweeps and the final hero frame while protecting product identity.",
    priceUsdCents: 2400,
    isFree: false,
    category: "Product Video",
    version: "V1.7",
    featured: true,
    deliverables: ["Complete Skill file", "Five lighting directions", "Category-based prompt examples", "Product replacement guide"],
    outcomes: ["Logos and silhouettes remain recognizable", "Lighting feels intentional", "Every sequence ends on a clear hero frame"],
  },
  {
    ...product,
    slug: "clean-unboxing-flow",
    name: "Clean Unboxing Starter",
    eyebrow: "A free, focused unboxing workflow",
    shortDescription: "Learn the basic unboxing sequence: open, remove, arrange and reveal without changing the packaging.",
    description: "A free starter Skill for testing the Skillroom workflow. It separates opening, item removal, tabletop arrangement and product close-up into clear stages.",
    priceUsdCents: 0,
    isFree: true,
    category: "Product Video",
    version: "V1.0",
    deliverables: ["Starter Skill file", "Four-step unboxing structure", "Packaging continuity checklist"],
    outcomes: ["Packaging keeps its original color", "Removed accessories stay in place", "Frames remain clean and readable"],
  },
  {
    ...product,
    slug: "miniature-workshop-story",
    name: "Miniature Workshop Story",
    eyebrow: "A tiny crew built around your product",
    shortDescription: "Create a short miniature story while keeping the product as the visual hero.",
    description: "A playful commercial Skill that controls character scale, props and product identity across a miniature workshop narrative.",
    priceUsdCents: 2600,
    isFree: false,
    category: "Product Video",
    version: "V1.3",
    deliverables: ["Complete Skill file", "Six story situations", "Miniature-scale rules", "Customization guide"],
    outcomes: ["Characters keep a stable scale", "The product remains the focal point", "The story has a clear beginning and ending"],
  },
  {
    ...aquascape,
    slug: "forest-diorama-aquascape",
    name: "Forest Diorama Aquascape",
    eyebrow: "Depth, wood scale and believable wet zones",
    shortDescription: "Build a submerged forest with strong perspective and natural visual pathways.",
    description: "A detailed Skill for controlling driftwood scale, moss placement and foreground plants without breaking biological or aquarium logic.",
    priceUsdCents: 2800,
    isFree: false,
    category: "Aquascape",
    version: "V1.7",
    deliverables: ["Complete Skill file", "Forest perspective preset", "Four scene-building prompts", "Biological logic checklist"],
    outcomes: ["Moss stays in suitable wet areas", "Wood scale creates believable depth", "Plants never grow through the glass"],
  },
  {
    ...automotive,
    slug: "jdm-garage-transformation",
    name: "JDM Garage Transformation",
    eyebrow: "A consistent build from empty shop to finished car",
    shortDescription: "Tell a garage restoration story with a controlled vehicle and environment state.",
    description: "A transformation Skill that locks bodywork, wheels, paint and garage structure at every milestone in the restoration timeline.",
    priceUsdCents: 3200,
    isFree: false,
    category: "Automotive",
    version: "V1.2",
    deliverables: ["Complete Skill file", "Five timeline prompts", "Vehicle-state table", "Garage replacement guide"],
    outcomes: ["The car progresses in the correct order", "The garage structure stays stable", "Paint color remains consistent"],
  },
  {
    ...product,
    slug: "food-commercial-motion",
    name: "Food Commercial Motion",
    eyebrow: "Appetizing ingredient motion and a clean final pack shot",
    shortDescription: "Direct short food commercials with readable ingredients, texture and product identity.",
    description: "A compact Skill for food and beverage motion, balancing dynamic ingredient movement with a clear branded hero shot.",
    priceUsdCents: 2500,
    isFree: false,
    category: "Product Video",
    version: "V1.1",
    deliverables: ["Complete Skill file", "Five motion structures", "Food and beverage prompt examples", "Vertical-format guide"],
    outcomes: ["Ingredients remain recognizable", "Motion avoids visual clutter", "The final frame clearly shows the label"],
  },
];

export const pageSize = 6;

export function getSkill(slug: string) {
  return skills.find((skill) => skill.slug === slug);
}

export function getSkillsPage(page: number) {
  const pages = Math.max(1, Math.ceil(skills.length / pageSize));
  const safePage = Math.min(Math.max(Math.trunc(page) || 1, 1), pages);
  const start = (safePage - 1) * pageSize;
  return {
    items: skills.slice(start, start + pageSize),
    page: safePage,
    pages,
    total: skills.length,
  };
}
